# Generated by Django 4.2.6 on 2023-10-19 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_artistic_name_user_full_name_and_more'),
        ('albums', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='users.user'),
        ),
    ]
